# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 172800 # Floofstation - 48 hours
    - !type:CharacterPlaytimeRequirement # Floof - Imagine a CMO who CAN'T do chems
      tracker: JobChemist
      min: 43200 # Floofstation - 12 hours
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Paramedic # DeltaV - Add Paramedic access
  - External # DeltaV - Paramedics need this access
  - Psychologist # DeltaV - Add Psychologist access
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 2.5

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    id: CMOPDA
    ears: ClothingHeadsetCMO
  innerClothingSkirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelCMOFilled
  duffelbag: ClothingBackpackDuffelCMOFilled
