- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  setPreference: true #floof - this toggle allows players to ready up / create loadouts as senior roles. false disables it from the job list.
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 432000 # Floofstation - 120 hrs
    - !type:CharacterPlaytimeRequirement # Floof - Imagine a teaching role who doesn't know chem which they're supposed to teach.
      tracker: JobChemist
      min: 43200 # Floofstation - 12 hours
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
# Floof section - Senior physicians get paramedic and external access  
  - Paramedic
  - External
# Floof section end
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 2.0

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
