- type: latheRecipe
  id: GrenadeFlashBang
  result: GrenadeFlashBang
  completetime: 3
  materials:
    Steel: 100
    Plastic: 100

# Ammo
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumLeverRifleEmpty
  result: MagazineMagnumLeverRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumLeverRifle
  result: MagazineMagnumLeverRifle
  materials:
    Steel: 185

- type: latheRecipe
  parent: BaseGoldCircuitboardRecipe
  icon: { sprite: _Goobstation/Structures/Machines/contraband_detector.rsi, state: icon }
  id: ContrabandDetectorCircuitboard
  result: ContrabandDetectorCircuitboard
  completetime: 4
